# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

# ThymeleafProperties
spring:
  thymeleaf:
    cache: false

  # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 773835
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong

# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# logger
logging:
  level:
    com.nowcoder.community: debug